name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Executar testes unitários
      run: node --test

    - name: Enviar notificação no Discord
      uses: Ilshadur/action-discord@0.3.2
      if: always() # Garante que envia alerta mesmo se os testes falharem
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: 'O pipeline do projeto projeto-automacao foi executado!'